export const friendsList = [
  {
    email: 'bob@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob1@test.com',
    status: 'invited',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob2@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob3@test.com',
    status: 'invited',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob4@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob5@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob6@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob7@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
  {
    email: 'bob8@test.com',
    status: 'joined',
    dateInvited: 'test',
    dateJoined: 'yes',
  },
];
