name: Setup Bref & Serverless
description: setup the deployment tool and aws cli

inputs:
  node-version:
    description: Node Version
    required: false
    default: 16.x
  npm-version:
    description: NPM Version
    required: false
    default: 7.10.0

runs:
  using: composite
  steps:
    - name: Setup Node ${{ inputs.node-version }} Environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ inputs.node-version }}

    - name: Upgrade npm to ${{ inputs.npm-version }}
      shell: bash
      run: npm i -g npm@${{ inputs.npm-version }}

    - name: Check node version
      shell: bash
      run: |
        node -v
        npm -v

    - name: Install Serverless cli
      shell: bash
      run: npm install -g serverless

    - name: Install Yarn
      shell: bash
      run: |
        npm install --global yarn
        yarn -v
