name: frontend (Build & Deploy)

on:
  push:
    branches: [develop]
    paths:
      - FE/**
      - .github/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: FE

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node

      - name: Set ENV Variables
        run: cp .env.dev .env.production

      - name: Install Dependencies
        run: yarn install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: us-east-1

      - name: Deploy
        run: npx serverless@2.72.2
