name: backend

on:
  push:
    branches: [staging]
    paths:
      - api/**
      - .github/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.0'
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.staging', '.env');"

      - name: Install Dependencies
        run: |
          composer install
          npm install

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Clear Config
        run: php artisan config:clear

      - name: Setup AWS Keys
        run: serverless config credentials --provider aws --key ${{ secrets.STG_AWS_ACCESS_KEY_ID }} --secret ${{ secrets.STG_AWS_ACCESS_SECRET }}

      - name: Deploy to Lambda
        run: serverless deploy --stage staging

      - name: Database Migration
        run: vendor/bin/bref cli laravel-staging-artisan -- migrate
